name: flutter_application_1
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cunning_document_scanner: ^1.1.2
  path_provider: ^2.0.13
  flutter_native_image: ^0.0.6+1
  isolate_image_compress: ^2.0.0
  flutter_pdfview: ^1.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  printing: ^5.10.1
  syncfusion_flutter_pdfviewer: ^20.4.51

flutter:
  uses-material-design: true
